version: "3"

services:
 #mongo Db 
  db: 
    image: mongo:latest
    restart: unless-stopped
    volumes:
      
       - /var/lib/docker/volumes/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: legolego
      MONGO_INITDB_DATABASE: django_mongodb_docker
      MONGODB_DATA_DIR: /var/lib/docker/volumes/mongo
    ports:
      - 27017:27017
    

  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/lego2me/
    expose:
      - 8000
    depends_on:
      - db

  #django
  # frontend:
  #   build:
  #     context: ./frontend
  #     #command: ["npm", "start"]
  #   ports:
  #     - 80:3000
  #   volumes:
  #     - ./frontend/:/frontend
  #    # - ./frontend/node_modules/:/frontend/node_modules
  #   environment:
  #     - CI=true
  #     - CHOKIDAR_USEPOLLING=true
  #   tty: true

  # flask:
  #   build: ./ai_flask_api
  #   volumes:
  #     - ./ai_flask_api:/ai_flask_api
  #   ports:
  #     - '5000:5000'

volumes:
  lego2me: